### ISSUE TITLE
About DEX files

### ISSUE THREAD

**Issue by sunxiaobiu** [Mohannadcse/DINA#1]
Hi, I tried to run DINA on my Mac, when I input the command "./launch --path ../../../apks" in the shell I encountered an error:
"libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: failed to open ../../../dex/framework/core.dex"

It seems that some pre-defined files are needed in the path of /dex, however, I didn't find any clues in Readme. So could u please give me hand, many thanks!

**Comment by Mohannadcse** [comment]
We didn't provide these files due to licensing issues. But I already email you the files.
