### ISSUE TITLE
About DEX Files

### ISSUE THREAD

**Issue by WaOoooooo** [Mohannadcse/DINA#3]
Hi , Markdown! When I  tried to use the DINA on Ubuntu ,I find a error.
erminate called after throwing an instance of 'std::runtime_error'
  what():  failed to open ../../../dex/framework/core.dex

	Could you  email me the files. Thank you very much!

**Comment by Mohannadcse** [comment]
what's your email?

**Comment by WaOoooooo** [comment]
> 你的电子邮件是什么？

kikychong@163.com
Very happy to receive your reply,thanks very much.

**Comment by Mohannadcse** [comment]
done. I'll close the issue if no more issues
